"""
FastAPI application initialization and startup.

Responsibility
    Create the FastAPI app, wire up middleware, register routes, configure logging.
    Routes are registered from api/routers/.

Must not
    Contain business logic (that is services/).
    Instantiate adapters directly (that is factories.py).
    Define routes inline (define them in api/routers/ and import them).

Startup flow
    1. Load settings from environment (config.py)
    2. Initialize database connection (persistence/)
    3. Build adapters from config (factories.py)
    4. Create FastAPI app
    5. Register middleware and routes
    6. Ready to serve
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from contextlib import asynccontextmanager

from praman.config import settings
from praman import __version__
from praman.api.routers import events as events_router
from praman.api.routers import certificates as certificates_router
from praman.api.routers import governance as governance_router
from praman.persistence.database import init_database
from praman.observability.otel import init_otel


# Startup / Shutdown events
@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Lifespan context manager for startup/shutdown.

    Startup: Initialize resources (database, adapters).
    Shutdown: Clean up resources.
    """
    # Startup
    #
    # No emoji in these messages: Windows consoles default to the cp1252
    # codepage, which cannot encode them, and uvicorn's startup print()
    # crashes the whole lifespan (and therefore the server) before a single
    # request is served. Plain ASCII works on every platform this runs on.
    #
    # The database host is logged, never the full DATABASE_URL — that string
    # carries the connection password, and startup logs are not a secret
    # store.
    db_host = settings.database_url.split("@")[-1].split("/")[0]
    print(f"Praman {__version__} starting ({settings.environment} mode)")
    print(f"Database host: {db_host}")
    print(f"Modules: privacy={settings.module_privacy_enabled}, ai_risk={settings.module_ai_risk_enabled}")

    # Initialize OpenTelemetry (optional; disabled by default in development)
    try:
        tracer, meter = init_otel(
            enabled=settings.otel_enabled,
            exporter_endpoint=settings.otel_exporter_otlp_endpoint,
            service_name=settings.otel_service_name,
            environment=settings.otel_environment,
        )
        print(f"OTel: {'enabled' if settings.otel_enabled else 'disabled'}")
    except Exception as e:
        print(f"OTel initialization warning: {e}")

    # Initialize database (run migrations)
    try:
        init_database()
    except Exception as e:
        print(f"Database initialization warning: {e}")

    yield

    # Shutdown
    print("Praman shutting down")


# Create app
app = FastAPI(
    title="Praman",
    description="Tamper-evident evidence engine for regulated AI in India",
    version=__version__,
    lifespan=lifespan,
)

# Middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # For demo; restrict in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Register routers
app.include_router(events_router.router, prefix="/events", tags=["events"])
app.include_router(certificates_router.router, prefix="/certificates", tags=["certificates"])
app.include_router(governance_router.router, prefix="/governance", tags=["governance"])

# Routes
@app.get("/health")
async def health_check():
    """
    Health check endpoint.

    Returns application status and version. Used by load balancers and
    monitoring systems to verify the app is alive.

    Response:
        - status: "ok" if healthy
        - version: application version
    """
    return {
        "status": "ok",
        "version": __version__,
        "environment": settings.environment,
        "modules": {
            "privacy": settings.module_privacy_enabled,
            "ai_risk": settings.module_ai_risk_enabled,
        },
    }


# Root
@app.get("/")
async def root():
    """
    Root endpoint. Links to documentation and dashboards.
    """
    return {
        "app": "Praman",
        "version": __version__,
        "docs": "/docs",  # Swagger UI (auto-generated by FastAPI)
        "redoc": "/redoc",  # ReDoc (auto-generated)
        "status": "/health",
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "praman.main:app",
        host="0.0.0.0",
        port=settings.port,
        reload=settings.is_development(),
        log_level=settings.log_level,
    )
